#服务名
spring:
  application:
    name: beacon-test
  # nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.130:8848
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.91.130:3306/beacon_cloud?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
# 端口号
server:
  port: 20000
# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
feign:
  client:
    config:
      default:
        connect-timeout: 600000 #feign连接超时时间
        read-timeout: 600000
