#服务名称
spring:
  # 服务名称
  application:
    name: beacon-webmaster
  # 多环境
  profiles:
    active: dev
  # nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.130:8848
        #nacos配置中心地址:
      config:
        server-addr: 192.168.91.130:8848
        file-extension: yml
        # beacon-webmaster-dev.yml
server:
  port: 10004
shiro:
  # 默认登录页面
  loginUrl: /login.html
  # 没有权限的页面
  unauthorizedUrl: unauthorized.html